services:
  - type: web
    name: portfolio-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
    disk:
      name: portfolio-disk
      mountPath: /mnt/data
      sizeGB: 1
